<div id="footer">
		<div id="footer-menu">
			<ul>
				<li><a href="#">Strona główna</a></li> <li><a href="#">O nas</a></li> <li><a href="#">Sklep</a></li> <li><a href="#">Przepisy</a></li                > <li><a href="#">Nasi partnerzy</a></li>
			</ul>
		<div id="footer-logo"><img src="images/footer-logo.png" alt="Eko Portal" /></div>
		<div id="site-map"><a href="#">Mapa strony</a></div>
		<div id="author"><a href="http://adrianszumski.com">Projekt & wykonanie: www.adrianszumski.com</a></div>
		</div>
	</div>
	<div id="fotter-bottom"></div>
</body>
</html>
