<!DOCTYPE html>
	<html lang="pl">
	<head>
	 	<meta charset="utf-8" />
		<link rel="stylesheet" type="text/css" href="css/style.css" />
		<title>Eko portal - Jedz pysznie ...</title>
		<script type="text/javascript" src="script/jquery.js"></script>
		<script type="text/javascript" src="script/motto.js"></script>
		<script type="text/javascript" src="script/product.js"></script>

		<script type="text/javascript">
			WebFontConfig = {
			google: { families: [ 'Oswald::latin', 'Indie+Flower::latin' ] }
			};
			(function() {
			var wf = document.createElement('script');
			wf.src = 'script/fonts.js';
			wf.type = 'text/javascript';
			wf.async = 'true';
			var s = document.getElementsByTagName('script')[0];
			s.parentNode.insertBefore(wf, s);
		})(); </script>
	</head>
	<body>
		<div id="header"><div id="motto">Jedz pysznie ...</div></div>
			<div id="menu">

				<ul id="menu-button">
				<li><a href="#"><img src="images/button1.png" onmouseover="src='images/button1-act.png'" onmouseout="src='images/button1.png'" alt="Nowości" /></a></li>
				<li><a href="#"><img src="images/button2.png" onmouseover="src='images/button2-act.png'" onmouseout="src='images/button2.png'" alt="O nas" /></a></li>
				<li><a href="#"><img src="images/button3.png" onmouseover="src='images/button3-act.png'" onmouseout="src='images/button3.png'" alt="Sklep" /></a></li>
				<li><a href="#"><img src="images/button4.png" onmouseover="src='images/button4-act.png'" onmouseout="src='images/button4.png'" alt="Przepisy" /></a></li>
			</ul>
		</div>