	<div style="padding: 15px;">
        <div style="color: #FFFFFF; font-family: 'Oswald'; font-size: 25px;" >Newsletter:</div>
		<div style="color: #FFFFFF; font-family: 'Oswald'; padding-top:15px;" >Najświeższe cotygodniowe informacje od naszych ekspertów:</div>
        <br />
        <form action="#" method="post">
        <input type="text" name="e-mail" value="Twój e-mail ..." style="height:25px; width: 180px;" />
        <br /><br />
        <div style="color: white; font-family:Verdana, Geneva, sans-serif; font-size: 10px; text-decoration:inherit;">Akceptuję politykę prywatności</div>
        <br />
        <input type="submit" style="background: url(images/save.png); width: 98px; height: 35px; border:0; background-repeat: no-repeat; cursor: pointer;" name="send" value="" />
        </form>
        <div style="padding-top:50px; font-family: 'Oswald'; font-size: 25px; color:#FFFFFF;">
        W tym tygodniu polecamy:
        <br />
        <br />

        <div class="product">
        <a href="#"><img src="images/1.png" alt="Produkt 1" style="" /></a>
        <a href="#"><img src="images/2.png" alt="Produkt 2" style="" /></a>
        <a href="#"><img src="images/3.png" alt="Produkt 2" style="" /></a>
        </div>
        <br />

        <div style="font-size:15px;">Zapraszamy do naszego e-sklepu</div>

        </div>
    </div>